controllers/BlogController.php
<?php

namespace app\controllers;

use app\models\Menu;
use app\models\News;
use app\models\search\NewsSearch;

class BlogController extends FrontendController
{
    public function actionArticles()
    {
        $menu = Menu::findOne(['url' => '/blog/articles']);
        $this->setMeta($menu->metaName, $menu->metaDesc, $menu->metaKey);

        $searchModel    = new NewsSearch();
        $dataProvider   = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('articles', compact('menu', 'searchModel', 'dataProvider'));
    }

    public function actionArticle($slug)
    {
        $menu   = Menu::findOne(['url' => '/blog/articles']);

        $article = News::findOne(['slug' => $slug]);
        $this->setMeta($article->metaName, $article->metaDesc, $article->metaKey);

        return $this->render('blog', compact('article', 'menu'));
    }
}

views/blog/articles.php
<?php

/* @var $this View */
/* @var $searchModel NewsSearch */
/* @var $menu \app\models\Menu */

/* @var $dataProvider ActiveDataProvider */

use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use app\models\search\NewsSearch;

$count  = count($dataProvider->models);

?>
<div class="blogs">
    <div class="container">
        <div class="row mt-5 mb-5">
            <div class="col-xl-3 col-md-4 col-sm-5 col-8">
                <?= $this->render('/partials/breadcrumbs', compact('menu')) ?>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-xl-12 col-12">
                <h1><?= $menu->name; ?></h1>
            </div>
        </div>
        <div class="row">
            <? foreach($dataProvider->models as $model): ?>
                <div class="col-xl-3 col-md-4 col-sm-6 col-12">
                <a href="<?= Url::to(['/blog/article', 'slug' => $model->slug]) ?>">
                    <div class="article__block">
                        <div class="img__wrapper">
                            <img src="<?= $model->getImage(); ?>">
                        </div>
                        <p><?= $model->title; ?></p>
                    </div>
                </a>
            </div>
            <? endforeach;?>
        </div>
        <div class="row mt-5">
            <div class="col-xl-6 col-12">
                <?= $this->render('/partials/pagination', [
                    'dataProvider' => $dataProvider,
                ]) ?>
            </div>
            <div class="col-xl-6 col-12 d-flex justify-content-end">
                <p class="total__services">
                    <? $text = '<span>' . $count . '</span>'?>
                    <?= $count == 0 ? '' : Yii::t('main', 'Всего {text}  Блогов',[
                        'text' => $text,
                    ]);?>
                </p>
            </div>
        </div>
    </div>
</div>

views/blog/blog.php
    <div class="blog">
        <div class="container">
            <div class="row mt-5 mb-5">
                <div class="col-xl-2 col-sm-3 col-md-2 col-6">
                    <?= $this->render('/partials/breadcrumbs', [
                            'menu'  => $menu,
                            'model' => $article,
                    ]) ?>
                </div>
            </div>
            <div class="row mb-5">
                <div class="col-xl-12 col-12">
                    <h1>
                        <?= $article->title; ?>
                    </h1>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12 col-12">
                    <div class="article__content">
                        <?= $article->description; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12 col-12">
                    <?= $article->content; ?>
                </div>
            </div>
        </div>
    </div>